### ISSUE TITLE
KeyError from unknown cause

### ISSUE THREAD

**Issue by leetrout** [okta/okta-aws-cli#104]
```
$ okta-awscli 
Enter password:
Enter MFA verification code: NNNNNN
Traceback (most recent call last):
  File "/Users/user/.asdf/installs/python/3.7.10/bin/okta-awscli", line 11, in <module>
    load_entry_point('okta-awscli==0.5.4', 'console_scripts', 'okta-awscli')()
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/oktaawscli/okta_awscli.py", line 142, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache, refresh_role, okta_username, okta_password
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/oktaawscli/okta_awscli.py", line 36, in get_credentials
    _, assertion = okta.get_assertion()
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/oktaawscli/okta_auth.py", line 157, in get_assertion
    self.session_id = self.get_session(self.session_token)
  File "/Users/user/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/oktaawscli/okta_auth.py", line 86, in get_session
    return resp['id']
KeyError: 'id'
```

Maybe related to the okta backend?

**Comment by monde** [comment]
Thanks @leetrout . You are having an issue with https://github.com/okta-awscli/okta-awscli which is community project.

This repo is for https://github.com/okta/okta-aws-cli/ which is the official Okta supported CLI to work with our AWS Federation apps.
